//------------------------------------------------------------------------
// Copyright(c) 2023 MMS SynthesizerPlugin.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"MMS SynthesizerPlugin.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"MMS SynthesizerPlugin VST3 (64Bit)"
#else
#define stringFileDescription	"MMS SynthesizerPlugin VST3"
#endif
#define stringCompanyName		"MMS SynthesizerPlugin\0"
#define stringLegalCopyright	"Copyright(c) 2023 MMS SynthesizerPlugin."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
